### ISSUE TITLE
Warning about nodejs

### ISSUE THREAD

**Issue by Freed-Wu** [softprops/action-gh-release#277] opened 2022-11-17 17:03 UTC
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: softprops/action-gh-release@v1
```

**Comment by cowboy-bebug** [comment] 2022-11-20 20:56
Duplicate of:
- https://github.com/softprops/action-gh-release/issues/249
- https://github.com/softprops/action-gh-release/issues/263

https://github.com/softprops/action-gh-release/pull/275 addresses it.

**Closed** 2022-11-21 04:29 UTC
