### ISSUE TITLE
Update to Node16

### ISSUE THREAD

**Issue by me-and** [softprops/action-gh-release#263] opened 2022-10-11 08:08 UTC
Per https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/, workflows using the latest version of this action are generating warnings like the below:

    Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/upload-artifact, softprops/action-gh-release, actions/upload-artifact

It looks like this isn't going to cause any serious problems until Summer 2023, but getting things migrated earlier rather than later seems like it'd be a good thing!

**Comment by auscompgeek** [comment] 2022-10-23 14:30
Duplicate of #249

**Comment by softprops** [comment] 2022-11-21 15:26
Fixed

**Closed by softprops** 2022-11-21 15:26 UTC
